import { z } from 'zod';

export const createStudyGroupSchema = z.object({
    name: z.string().min(3).max(100),
    description: z.string().max(500).optional(),
});

export type CreateStudyGroupInput = z.infer<typeof createStudyGroupSchema>;

export const updateStudyGroupSchema = createStudyGroupSchema.partial();

export type UpdateStudyGroupInput = z.infer<typeof updateStudyGroupSchema>;

export const addMembersSchema = z.object({
    memberIds: z.array(z.string()),
});

export type AddMembersInput = z.infer<typeof addMembersSchema>;

export const createResourceSchema = z.object({
    title: z.string().min(1).max(200),
    type: z.enum(['PDF', 'LINK']),
    url: z.string().optional(), // File upload URL will be generated by multer, LINK needs to provide it
});

export type CreateResourceInput = z.infer<typeof createResourceSchema>;
